[settings]
resolution = 24
scaling = 1.0
diffusion = 0         # Diffusion constant
dt = 1.0             # Timestep
viscosity = 0.000001  # Viscosity constant

# insert_position = [12, 12, 1]
# insert_velocity = [0, 0, 5]
insert_position = [1, 1, 1]
insert_velocity = [4, 4, 4]

[[obstacle]]
position = [12, 12, 14]
model = "resources/models/untitled_textures/untitled_texures.obj"
identifier = "plane"
scaling = [1, 1, 1]
enabled = true

[[obstacle]]
position = [12, 4, 12]
model = "resources/models/pyramid/pyramid.obj"
identifier = "pyramid"

[[obstacle]]
position = [12, 12, 12]
model = "resources/models/paper_airplane/plane.obj"
identifier = "paper_plane"

[[obstacle]]
position = [1,1,1]
model = "resources/models/cube.obj"
identifier = "cube"

[[obstacle]]
position = [12, 12, 12]
model = "resources/models/torus.obj"
identifier = "torus"
